### ISSUE TITLE
Fixing license

### ISSUE THREAD

**Issue by MichalStrehovsky** [ieviev/fflat#5]
Hello! Could you please bring this project in compliance with bflat license?

I see this tool is distributed under MIT license, but it's pulling down the bflattened/bflat repo that is AGPL. AGPL code cannot be included in MIT-licensed projects (it is possible to do this the other way around only). Two immediate possibilities:

* License the tool as AGPL instead, or
* Use the official binary releases of bflat (instead of the source code) that are licensed under the MIT license.

I don't have any problem with your project being based on bflat but the license of your project makes it possible for others to build on it in a way that I may have a problem with.

Thanks!

**Comment by ieviev** [comment]
Hello!

Sure, i will just change the license to AGPL, it's no problem

**Comment by MichalStrehovsky** [comment]
Thank you!
