### ISSUE TITLE
require C++ compiler for docker images (improve error message, LD_PATH is not the culprit)

### ISSUE THREAD

**Issue by jkone27** [ieviev/fflat#6]
https://github.com/ieviev/fflat/blob/989e4bc6fb3a5ac4aa9c8d3a5cc69710529c8708/src/fflat/Program.fs#L25

the message is ambiguous, but only c++ compiler is required to work in docker image

```docker
# Start with the existing dev container image
FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm

# Install libc++-dev and other dependencies
RUN apt-get update && apt-get install -y \
    libc++-dev \
    && rm -rf /var/lib/apt/lists/*

```

**Comment by ieviev** [comment]
ah, very good i will update this in the readme and error message.

i should add a full Dockerfile sample as well
